name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: test-206

    steps:
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TEST206 }}

      - name: Clone
        run: git clone git@github.com:Alipipe/top-dw-agent.git

      - name: Build
        run: bash .github/scripts/build.sh

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: dist/main
          retention-days: 1
